### ISSUE TITLE
Keycloak Test Realm Config for CWA

### ISSUE THREAD

**Issue by elenakalimera** [corona-warn-app/cwa-verification-iam#51]
Hello Guys,

first of all thanks a lot for the great work you are providing to the world!

As i am willing to test the different components with a goal to contribute back to this initiative, i was faced with the challenge to configure the cwa realm with all required clients and roles to make all pieces running. Can you please share an example JSON file configuration of the cwa realm for Keycloak? 

Thanks a lot in advance

**Comment by elenakalimera** [comment]
Hello Team,

any updates please on my question?

Thanks

**Comment by daniel-eder** [comment]
@elenakalimera I will raise this once more in our project daily tomorrow and ask our dev team to get back to you. Thank you!

**Comment by elenakalimera** [comment]
@daniel-eder Thanks a lot!

**Comment by chalbig-t-systems** [comment]
As soon as we have resources to implement a basic configuration of the cwa realm for the Keycloak in JSON format, we will adress this point in devolopment.

**Comment by daniel-eder** [comment]
I am sorry to say, but at this time the resource allocation does not allow to handle this issue. If a higher priority or critical issue arises out of this issue, please reopen this issue.
